import type { UpgradeDef } from './types';

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'soul_shard',
    name: 'Soul Shard',
    nameJP: '魂の欠片',
    description: "A fragment of a fallen warrior's spirit, still warm to the touch. Mends the wounds of flesh and grants one more chance to prove your worth against the rising tide.",
    price: 300,
    maxLevel: 2,
    icon: '♥',
    iconColor: '#FF0080',
  },
  {
    id: 'chrono_slice',
    name: 'Chronoslice Protocol',
    nameJP: '時間切断',
    description: 'Ancient runes etched into the blade slow the very weave of time. Critical strikes freeze the world twice as long — enough to line up the next perfect strike before reality catches up.',
    price: 250,
    maxLevel: 1,
    icon: '⊙',
    iconColor: '#00FFFF',
  },
  {
    id: 'fortune_magnet',
    name: 'Fortune Magnet',
    nameJP: '黄金の引力',
    description: 'Enchanted lodestone dust rubbed into your fingertips. Golden cookies sense your desire and drift toward your blade, their aura helplessly drawn into your strike zone.',
    price: 150,
    maxLevel: 1,
    icon: '★',
    iconColor: '#FFD700',
  },
  {
    id: 'phantom_thread',
    name: 'Phantom Thread',
    nameJP: '幻のスレッド',
    description: 'Invisible silk stitches each strike to the next, carrying momentum across the gap. Your combo window stretches wider — a heartbeat\'s hesitation won\'t shatter the chain.',
    price: 175,
    maxLevel: 2,
    icon: '∞',
    iconColor: '#9B00FF',
  },
  {
    id: 'blast_rune',
    name: 'Blast Rune',
    nameJP: '爆破の符',
    description: 'A forbidden ward burned into your palm with shadow-ink. Once per wave the rune flares, swallowing an explosion whole — then shatters to dust, its sacrifice complete.',
    price: 400,
    maxLevel: 1,
    icon: '✦',
    iconColor: '#FF4400',
  },
  {
    id: 'ghost_multiplier',
    name: 'Ghost Multiplier',
    nameJP: '亡霊の残響',
    description: 'A spectral echo haunts every slice, mimicking your movement in the spirit realm. Fifteen percent of the time the ghost scores its own cut — doubling your take without lifting a finger.',
    price: 350,
    maxLevel: 1,
    icon: '◑',
    iconColor: '#AA88FF',
  },
  {
    id: 'spirit_overflow',
    name: 'Spirit Overflow',
    nameJP: '霊力爆発',
    description: 'Your reservoir of spiritual energy can no longer be contained by mortal flesh. Every tenth cookie sliced triggers a reiki surge, flooding your reserves with raw spiritual currency.',
    price: 225,
    maxLevel: 2,
    icon: '◉',
    iconColor: '#FFE600',
  },
  {
    id: 'crumb_accelerator',
    name: 'Crumb Accelerator',
    nameJP: '加速の刃',
    description: 'The blade drinks momentum like sake. High-velocity slashes carry a far greater chance of triggering a critical hit — the faster your hand, the deadlier the outcome.',
    price: 200,
    maxLevel: 1,
    icon: '►',
    iconColor: '#00FF88',
  },
];
