import type { AchievementDef } from './types';

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_slice',
    name: 'First Blood',
    nameJP: '初斬り',
    description: 'Slice your very first cookie. The journey of a thousand cuts begins here.',
    icon: '🍪',
    iconColor: '#D4955A',
  },
  {
    id: 'combo_10',
    name: 'Chain Striker',
    nameJP: '連続斬',
    description: 'Land a 10-hit combo in a single run. Keep the rhythm going.',
    icon: '⚡',
    iconColor: '#FFE600',
  },
  {
    id: 'combo_30',
    name: 'Neon Tempest',
    nameJP: 'ネオン嵐',
    description: 'Reach a 30-hit combo. Your blade becomes a blur of neon light.',
    icon: '🌪',
    iconColor: '#FF0080',
  },
  {
    id: 'combo_50',
    name: 'Phantom Blade',
    nameJP: '幻刃',
    description: 'Hit 50 consecutive cookies. At this speed the world holds its breath.',
    icon: '⚔',
    iconColor: '#9B00FF',
  },
  {
    id: 'score_5000',
    name: 'Street Rookie',
    nameJP: '街の新人',
    description: 'Rack up 5,000 points. The neon district takes notice of your skill.',
    icon: '★',
    iconColor: '#44CCFF',
  },
  {
    id: 'score_25000',
    name: 'Arcade Legend',
    nameJP: 'アーケードの伝説',
    description: 'Score 25,000 points. Your name burns bright on the leaderboard.',
    icon: '🏆',
    iconColor: '#FFD700',
  },
  {
    id: 'score_100000',
    name: 'God of Blades',
    nameJP: '刃の神',
    description: 'Reach 100,000 points. Legends are written in your wake.',
    icon: '👑',
    iconColor: '#FF6600',
    secret: true,
  },
  {
    id: 'wave_5',
    name: 'Rising Tide',
    nameJP: '波濤',
    description: 'Survive until Wave 5. The cookie hordes grow ever more relentless.',
    icon: '🌊',
    iconColor: '#00FFFF',
  },
  {
    id: 'wave_10',
    name: 'Unstoppable',
    nameJP: '無敵',
    description: 'Reach Wave 10. Most samurai fall before this point.',
    icon: '🔥',
    iconColor: '#FF4400',
  },
  {
    id: 'golden_10',
    name: 'Fortune Hunter',
    nameJP: '黄金の猟師',
    description: 'Slice 10 golden cookies across all your runs. Fortune favors the bold.',
    icon: '✨',
    iconColor: '#FFD700',
  },
  {
    id: 'bomb_blocked',
    name: 'Rune Warden',
    nameJP: 'ルーンの番人',
    description: 'Use the Blast Rune to nullify a bomb explosion. Sacrifice to survive.',
    icon: '🛡',
    iconColor: '#FF4400',
  },
  {
    id: 'slices_100',
    name: 'Centurion',
    nameJP: '百斬り',
    description: 'Slice 100 cookies total across all games. A respectable body count.',
    icon: '⚡',
    iconColor: '#44FF88',
  },
  {
    id: 'slices_1000',
    name: 'Master Slasher',
    nameJP: '斬りの達人',
    description: 'Slice 1,000 cookies total. The blade is an extension of your will.',
    icon: '⚔',
    iconColor: '#00FFFF',
    secret: true,
  },
  {
    id: 'max_reiki',
    name: 'Spirit Overflow',
    nameJP: '霊気の溢れ',
    description: 'Accumulate 1,000 Reiki in a single session. Your spirit burns like a sun.',
    icon: '◉',
    iconColor: '#FFE600',
  },
  {
    id: 'perfect_hp',
    name: 'Untouchable',
    nameJP: '無傷',
    description: 'Complete Wave 3 without losing a single life. Pure elegance.',
    icon: '💎',
    iconColor: '#00FFFF',
    secret: true,
  },
];
